### ISSUE TITLE
Installation on Mac OSX

### ISSUE THREAD

**Issue by lolobosse** [diraimondo/gmusicproxy#8]
Hi,

Hope you don't mind but I tried on a OSX and it does not work out from the box (i mean as you described on the website). Here are the different things I tried to install it on OSX 10.9 and the different errors I got :
- "sudo pip install https://github.com/diraimondo/gmusicproxy/tarball/master"
  --> No distributions matching the version for gmusicapi>=3.1.1-dev (from gmusicproxy==0.9.4)
- By cloning the repository, happily, it's the same error.
- By downloading the last TAR, it's a bit more complicated because I get many warning easily fixable, but, at the end I cannot succeed to install ; here are the different problems :
  - A problem with eyed3 dependency (which can be resolved with "sudo pip install . --allow-external eyed3 --allow-unverified eyed3")
    ![screen shot 2014-03-22 at 15 42 34](https://f.cloud.github.com/assets/5024077/2490934/523c1e14-b1d0-11e3-9a0e-6f1212201c09.png)
  - Then come a problem which seems much more serious with this stack trace : Command /usr/bin/python -c "import setuptools, tokenize;**file**=u'/private/tmp/pip_build_root/netifaces/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-5fWkJ5-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /private/tmp/pip_build_root/netifaces
    ![screen shot 2014-03-22 at 15 50 25](https://f.cloud.github.com/assets/5024077/2490943/68561a96-b1d1-11e3-87f3-3e8b2a26f032.png)
    (EDIT) I went further on that problem and it's caused by netifaces and I got this problem on all its version of it (it's not linked to your soft but prevent it to work). Didn't found any solutions on the Internet, maybe, if you have one, it would be very appreciable ! I'll test on Linux yet !
- Currently, I'm blocked here and I cannot test your project which sounds to be great but does not work because of dependencies :(

Hope it helps to improve it !

**Comment by racl101** [comment]
I just tried this on Mac OS X Yosemite and still had some problems with the syntax. This is what worked for me:

`$ sudo -H pip install --allow-external eyeD3 --allow-unverified eyeD3 eyeD3`

Had to specify `eyeD3` three times, two for each switch and one for the actual package I'm installing. Talk about confusing, non-intuitive syntax. The `-H` flag after sudo is for if you get these messages while trying to install:

`The directory '/Users/<myusername>/Library/Logs/pip' or its parent directory is not owned by the current user and the debug log has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
The directory '/Users/<myusername>/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
The directory '/Users/<myusername>/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
`

Since I'm the only user on this machine I don't think it should matter if I set the -H flag while running sudo but if there's a problem, someone let me know  please.
